spring:
  datasource:
    url: jdbc:mysql://192.168.128.132:3306/dm_user?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: dm-user-provider
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
moduleName: dm-user-provider
server:
  port: 7011
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
